# This file is generated by the scaffold script below.
# Replace or extend as you iterate—keep it simple and readable.

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

os.makedirs("reports/tables", exist_ok=True)
os.makedirs("reports/figures", exist_ok=True)

df = pd.read_csv("data/sample/transactions.csv")
mu = df["amount"].mean()
sd = df["amount"].std(ddof=0)
if not sd or sd == 0:
    sd = 1.0

df["z"] = (df["amount"] - mu) / sd
flags = df[df["z"].abs() >= 3.0]
flags.to_csv("reports/tables/anomalies.csv", index=False)

plt.figure()
plt.hist(df["amount"], bins=10)
plt.title("Transaction amounts (sample)")
plt.xlabel("amount"); plt.ylabel("freq")
plt.tight_layout()
plt.savefig("reports/figures/amount_hist.png", dpi=160)
print("Wrote reports/tables/anomalies.csv and reports/figures/amount_hist.png")

